"""add a column is_root to users table

Revision ID: 127176bd869
Revises: 24095188057
Create Date: 2015-05-16 15:43:20.303451

"""

# revision identifiers, used by Alembic.
revision = '127176bd869'
down_revision = '24095188057'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_root', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_root')
    ### end Alembic commands ###
