"""create websites, columns, articles table

Revision ID: 1b1cc717661
Revises: 
Create Date: 2015-05-15 22:26:56.724271

"""

# revision identifiers, used by Alembic.
revision = '1b1cc717661'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websites',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('columns',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('layer', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('parent', sa.String(length=20), nullable=True),
    sa.Column('website_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('column_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    op.drop_table('columns')
    op.drop_table('websites')
    ### end Alembic commands ###
