"""create users table

Revision ID: 24095188057
Revises: 7db0e4e901
Create Date: 2015-05-16 15:26:43.888041

"""

# revision identifiers, used by Alembic.
revision = '24095188057'
down_revision = '7db0e4e901'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('nickname', sa.String(length=40), nullable=True),
    sa.Column('website_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
