"""add description column to websites table

Revision ID: 2b79083066e
Revises: 2fb246ff7ce
Create Date: 2015-05-23 19:09:10.430426

"""

# revision identifiers, used by Alembic.
revision = '2b79083066e'
down_revision = '2fb246ff7ce'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'description')
    ### end Alembic commands ###
