"""Alter email belong to users to username

Revision ID: 2fb246ff7ce
Revises: 127176bd869
Create Date: 2015-05-17 16:51:19.532503

"""

# revision identifiers, used by Alembic.
revision = '2fb246ff7ce'
down_revision = '127176bd869'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    op.drop_column('users', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('users', 'username')
    ### end Alembic commands ###
