"""add description column to columns table

Revision ID: 48969f4cf67
Revises: 2b79083066e
Create Date: 2015-05-24 10:26:02.015274

"""

# revision identifiers, used by Alembic.
revision = '48969f4cf67'
down_revision = '2b79083066e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('columns', sa.Column('description', sa.String(length=600), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('columns', 'description')
    ### end Alembic commands ###
