"""change all foreign keys to not nullable

Revision ID: 7db0e4e901
Revises: 1b1cc717661
Create Date: 2015-05-15 22:57:20.514355

"""

# revision identifiers, used by Alembic.
revision = '7db0e4e901'
down_revision = '1b1cc717661'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'column_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('columns', 'website_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('columns', 'website_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('articles', 'column_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    ### end Alembic commands ###
